#!/usr/bin/env python3
"""
Auto-generated cleanup script for TP2-4 remnants
Generated by analyze_pickle_tp_remnants.py
"""

import pickle
from pathlib import Path

def cleanup_tp_remnants():
    """Clean up TP2-4 remnants from pickle data."""
    pickle_path = "bybit_bot_dashboard_v4.1_enhanced.pkl"
    backup_path = f"{pickle_path}.backup_tp_cleanup_{int(__import__("time").time())}"

    # Create backup
    print(f'Creating backup: {backup_path}')
    import shutil
    shutil.copy2(pickle_path, backup_path)

    # Load data
    with open(pickle_path, 'rb') as f:
        data = pickle.load(f)

    # CRITICAL: Remove runtime-breaking references
    # WARNING: Clean up UI and chat data
    # Remove TP2-4 price fields from chat_data
    for chat_id, chat_info in data.get('chat_data', {}).items():
        if isinstance(chat_info, dict):
            if 'tp2_price' in chat_info:
                del chat_info['tp2_price']
                print(f'Removed tp2_price from chat {chat_id}')
            if 'tp3_price' in chat_info:
                del chat_info['tp3_price']
                print(f'Removed tp3_price from chat {chat_id}')
            if 'tp4_price' in chat_info:
                del chat_info['tp4_price']
                print(f'Removed tp4_price from chat {chat_id}')

    # Save cleaned data
    with open(pickle_path, 'wb') as f:
        pickle.dump(data, f)

    print('Cleanup completed successfully!')
    print(f'Backup saved as: {backup_path}')

if __name__ == '__main__':
    cleanup_tp_remnants()