services:
  - type: web
    name: bybit-telegram-bot
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      # Core Configuration (REQUIRED)
      - key: TELEGRAM_TOKEN
        sync: false
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      - key: USE_TESTNET
        value: false
      
      # OpenAI Integration (OPTIONAL)
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: openai
      - key: ENABLE_GPT4_REASONING
        value: true
      
      # Mirror Trading (OPTIONAL)
      - key: BYBIT_API_KEY_2
        sync: false
      - key: BYBIT_API_SECRET_2
        sync: false
      
      # Performance Configuration
      - key: LOG_LEVEL
        value: INFO
      - key: PERSISTENCE_FILE
        value: bybit_bot_dashboard_v4.1_enhanced.pkl
      
      # Enhanced Features
      - key: ENABLE_ENHANCED_TP_SL
        value: true
      - key: CANCEL_LIMITS_ON_TP1
        value: true
      - key: DYNAMIC_FEE_CALCULATION
        value: true
      - key: BREAKEVEN_FAILSAFE_ENABLED
        value: true
      - key: ENABLE_ENHANCED_MARKET_ANALYSIS
        value: true
      
      # Performance Optimizations
      - key: HTTP_MAX_CONNECTIONS
        value: 600
      - key: HTTP_MAX_CONNECTIONS_PER_HOST
        value: 150
      - key: ENABLE_CIRCUIT_BREAKER
        value: true
      - key: ENABLE_PERIODIC_MONITOR_CLEANUP
        value: true
    
    # Persistent disk for bot data
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1
    
    # Health check
    healthCheckPath: /health
    
    # Auto-deploy from main branch
    autoDeploy: true